# Generated by Django 5.1.15 on 2026-08-17 18:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(max_length=80, verbose_name="dispositivo")),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="fabricante"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=120, verbose_name="modelo"),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="certificado"
                    ),
                ),
                (
                    "certificate_valid_until",
                    models.DateField(blank=True, null=True, verbose_name="validade"),
                ),
            ],
            options={
                "verbose_name": "componente de segurança",
                "verbose_name_plural": "componentes de segurança",
            },
        ),
        migrations.CreateModel(
            name="EnergySource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("electric", "Elétrica"),
                            ("pneumatic", "Pneumática"),
                            ("hydraulic", "Hidráulica"),
                            ("thermal", "Térmica"),
                            ("gravitational", "Gravitacional"),
                            ("chemical", "Química"),
                            ("residual", "Residual"),
                        ],
                        max_length=16,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "magnitude",
                    models.DecimalField(
                        decimal_places=3, max_digits=10, verbose_name="magnitude"
                    ),
                ),
                ("unit", models.CharField(max_length=12, verbose_name="unidade")),
                (
                    "notes",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="observação"
                    ),
                ),
            ],
            options={
                "verbose_name": "fonte de energia",
                "verbose_name_plural": "fontes de energia",
            },
        ),
        migrations.CreateModel(
            name="LockoutPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identifier",
                    models.CharField(
                        max_length=40, verbose_name="identificação física"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="localização"
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="dispositivo de bloqueio",
                    ),
                ),
                (
                    "procedure_text",
                    models.TextField(
                        blank=True, verbose_name="etapa de bloqueio e verificação"
                    ),
                ),
            ],
            options={
                "verbose_name": "ponto de bloqueio",
                "verbose_name_plural": "pontos de bloqueio",
            },
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="identificação"),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="número de série"
                    ),
                ),
                (
                    "asset_tag",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="patrimônio"
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="fabricante"
                    ),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=120, verbose_name="modelo"),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="ano"
                    ),
                ),
                (
                    "capacity",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="capacidade"
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="peso (kg)",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "limits",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="limites do equipamento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativa"),
                            ("inactive", "Inativa"),
                            ("archived", "Arquivada"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "máquina",
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("plate", "Placa de identificação"),
                            ("front", "Frontal"),
                            ("back", "Traseira"),
                            ("left", "Lateral esquerda"),
                            ("right", "Lateral direita"),
                            ("general", "Geral"),
                            ("finding", "Constatação"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                ("file_key", models.CharField(max_length=300)),
                ("derivatives", models.JSONField(blank=True, default=dict)),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="legenda"
                    ),
                ),
                ("taken_at", models.DateTimeField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "link_kind",
                    models.CharField(
                        choices=[
                            ("checklist_item", "Item de checklist"),
                            ("hazard_zone", "Zona de perigo"),
                            ("action", "Ação de plano"),
                            ("machine", "Máquina"),
                            ("none", "Sem vínculo"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("link_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "fotografia",
                "verbose_name_plural": "fotografias",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=40, verbose_name="número")),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "art_number",
                    models.CharField(blank=True, max_length=40, verbose_name="ART"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("active", "Ativo"),
                            ("closed", "Encerrado"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
            ],
            options={
                "verbose_name": "projeto",
            },
        ),
    ]
