# Generated by Django 5.1.15 on 2026-08-21 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("nr12", "NR-12"),
                            ("nr10", "NR-10"),
                            ("nr17", "NR-17"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "library_base_count",
                    models.PositiveSmallIntegerField(verbose_name="base fixa"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Em coleta"),
                            ("collected", "Coletado"),
                            ("closed", "Encerrado"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "aplicação de checklist",
                "verbose_name_plural": "aplicações de checklist",
            },
        ),
        migrations.CreateModel(
            name="ItemResultRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("compliant", "Conforme"),
                            ("non_compliant", "Não conforme"),
                            ("partial", "Parcial"),
                            ("not_applicable", "Não aplicável"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "justification",
                    models.TextField(blank=True, verbose_name="justificativa"),
                ),
                ("note", models.TextField(blank=True, verbose_name="observação")),
                ("answered_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "resposta de item",
                "verbose_name_plural": "respostas de item",
                "db_table": "checklists_itemresult",
            },
        ),
        migrations.CreateModel(
            name="LibraryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "library_key",
                    models.CharField(max_length=40, verbose_name="identificador"),
                ),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("nr12", "NR-12"),
                            ("nr10", "NR-10"),
                            ("nr17", "NR-17"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="agrupamento"
                    ),
                ),
                ("statement", models.TextField(verbose_name="enunciado")),
                ("help_text", models.TextField(blank=True, verbose_name="orientação")),
                (
                    "annex",
                    models.CharField(blank=True, max_length=20, verbose_name="anexo"),
                ),
                (
                    "requires_evidence",
                    models.BooleanField(default=False, verbose_name="exige evidência"),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "item de biblioteca",
                "verbose_name_plural": "itens de biblioteca",
                "ordering": ("standard", "display_order"),
            },
        ),
        migrations.CreateModel(
            name="MachineType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "nr12_annexes",
                    models.JSONField(
                        blank=True, default=list, verbose_name="anexos aplicáveis"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("global", "Global"), ("tenant", "Do cliente")],
                        default="global",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de máquina",
                "verbose_name_plural": "tipos de máquina",
            },
        ),
    ]
