# Generated by Django 5.1.15 on 2026-08-17 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ativos", "0002_initial"),
        ("checklists", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="collected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="ativos.machine",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemresultrecord",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="checklists.assessment",
            ),
        ),
        migrations.AddField(
            model_name="itemresultrecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemresultrecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="itemresultrecord",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="libraryitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="libraryitem",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemresultrecord",
            name="library_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="results",
                to="checklists.libraryitem",
            ),
        ),
        migrations.AddField(
            model_name="machinetype",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="machinetype",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="machine_types",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="machinetype",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["tenant", "machine", "standard", "status"],
                name="checklists__tenant__4a43e1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="libraryitem",
            index=models.Index(
                fields=["standard", "display_order"],
                name="checklists__standar_e46a99_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="libraryitem",
            constraint=models.UniqueConstraint(
                fields=("standard", "library_key", "version"),
                name="checklists_libraryitem_chave_unica",
            ),
        ),
        migrations.AddIndex(
            model_name="itemresultrecord",
            index=models.Index(
                fields=["tenant", "result"], name="checklists__tenant__355660_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="itemresultrecord",
            constraint=models.UniqueConstraint(
                fields=("assessment", "library_item"),
                name="checklists_itemresult_unico_por_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemresultrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("result", "not_applicable"), _negated=True),
                    models.Q(("justification", ""), _negated=True),
                    _connector="OR",
                ),
                name="checklists_itemresult_na_exige_justificativa",
            ),
        ),
        migrations.AddConstraint(
            model_name="machinetype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("scope", "global")),
                fields=("name",),
                name="checklists_machinetype_nome_global_unico",
            ),
        ),
    ]
