# Generated by Django 5.1.15 on 2026-08-17 18:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ativos", "0001_initial"),
        ("checklists", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hazard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "zone",
                    models.CharField(max_length=120, verbose_name="zona de perigo"),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "iso12100_type",
                    models.CharField(
                        choices=[
                            ("mechanical", "Mecânico"),
                            ("electrical", "Elétrico"),
                            ("thermal", "Térmico"),
                            ("noise", "Ruído"),
                            ("vibration", "Vibração"),
                            ("radiation", "Radiação"),
                            ("material", "Material ou substância"),
                            ("ergonomic", "Ergonômico"),
                            ("environment", "Ambiente de trabalho"),
                            ("combination", "Combinação de perigos"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "lifecycle_phase",
                    models.CharField(
                        choices=[
                            ("operation", "Operação"),
                            ("setup", "Preparação"),
                            ("maintenance", "Manutenção"),
                            ("cleaning", "Limpeza"),
                            ("transport", "Transporte"),
                        ],
                        default="operation",
                        max_length=16,
                    ),
                ),
                (
                    "task",
                    models.CharField(blank=True, max_length=160, verbose_name="tarefa"),
                ),
                (
                    "existing_measures",
                    models.TextField(blank=True, verbose_name="medidas existentes"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hazards",
                        to="ativos.machine",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "perigo",
            },
        ),
        migrations.CreateModel(
            name="HrnEstimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("initial", "Inicial"), ("residual", "Residual")],
                        max_length=10,
                    ),
                ),
                (
                    "lo",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="probabilidade (LO)",
                    ),
                ),
                (
                    "fe",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="frequência (FE)"
                    ),
                ),
                (
                    "dph",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="gravidade (DPH)"
                    ),
                ),
                (
                    "np",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        verbose_name="pessoas expostas (NP)",
                    ),
                ),
                (
                    "product",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="HRN"
                    ),
                ),
                (
                    "band",
                    models.CharField(
                        choices=[
                            ("negligible", "Desprezível"),
                            ("very_low", "Muito baixo"),
                            ("low", "Baixo"),
                            ("significant", "Significante"),
                            ("high", "Alto"),
                            ("very_high", "Muito alto"),
                            ("extreme", "Extremo"),
                            ("unacceptable", "Inaceitável"),
                        ],
                        max_length=16,
                        verbose_name="faixa",
                    ),
                ),
                (
                    "method_version",
                    models.CharField(max_length=10, verbose_name="versão do método"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hazard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimates",
                        to="risco.hazard",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "estimativa de risco",
                "verbose_name_plural": "estimativas de risco",
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("normative", "Normativa"),
                            ("practice", "Boa prática"),
                        ],
                        default="normative",
                        max_length=12,
                    ),
                ),
                (
                    "iso12100_step",
                    models.CharField(
                        choices=[
                            ("inherent_design", "Projeto intrinsecamente seguro"),
                            ("safeguarding", "Proteção e medidas complementares"),
                            ("information", "Informação de uso"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text", models.TextField(verbose_name="medida proposta")),
                (
                    "device",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="dispositivo"
                    ),
                ),
                (
                    "deadline_days",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="prazo sugerido (dias)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hazard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="risco.hazard",
                    ),
                ),
                (
                    "standard_reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recommendations",
                        to="checklists.libraryitem",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recomendação",
                "verbose_name_plural": "recomendações",
            },
        ),
        migrations.CreateModel(
            name="SafetyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("s", models.PositiveSmallIntegerField(verbose_name="gravidade (S)")),
                ("f", models.PositiveSmallIntegerField(verbose_name="frequência (F)")),
                (
                    "p",
                    models.PositiveSmallIntegerField(
                        verbose_name="possibilidade de evitar (P)"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("b", "B"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "plr",
                    models.CharField(
                        choices=[
                            ("a", "a"),
                            ("b", "b"),
                            ("c", "c"),
                            ("d", "d"),
                            ("e", "e"),
                        ],
                        max_length=2,
                        verbose_name="PLr",
                    ),
                ),
                (
                    "rationale",
                    models.TextField(blank=True, verbose_name="justificativa"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hazard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="safety_category",
                        to="risco.hazard",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "categoria de segurança",
                "verbose_name_plural": "categorias de segurança",
            },
        ),
        migrations.AddIndex(
            model_name="hazard",
            index=models.Index(
                fields=["tenant", "machine"], name="risco_hazar_tenant__44686e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hazard",
            index=models.Index(
                fields=["tenant", "iso12100_type"],
                name="risco_hazar_tenant__4f0f17_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hrnestimate",
            index=models.Index(
                fields=["tenant", "band"], name="risco_hrnes_tenant__028ab5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="hrnestimate",
            constraint=models.UniqueConstraint(
                fields=("hazard", "kind"), name="risco_hrnestimate_unica_por_tipo"
            ),
        ),
        migrations.AddConstraint(
            model_name="hrnestimate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lo__gt", 0), ("fe__gt", 0), ("dph__gt", 0), ("np__gt", 0)
                ),
                name="risco_hrnestimate_fatores_positivos",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(
                fields=["tenant", "hazard"], name="risco_recom_tenant__dbee8c_idx"
            ),
        ),
    ]
