# Generated by Django 5.1.15 on 2026-08-21 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_name",
                    models.CharField(max_length=200, verbose_name="razão social"),
                ),
                ("tax_id", models.CharField(max_length=14, verbose_name="CNPJ")),
                (
                    "cnae",
                    models.CharField(blank=True, max_length=10, verbose_name="CNAE"),
                ),
                ("address", models.JSONField(blank=True, default=dict)),
                ("contact", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Ativo"), ("archived", "Arquivado")],
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "brand_logo_key",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="logo no armazenamento"
                    ),
                ),
                (
                    "brand_primary",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="cor primária"
                    ),
                ),
                (
                    "brand_secondary",
                    models.CharField(
                        blank=True, max_length=9, verbose_name="cor secundária"
                    ),
                ),
                (
                    "brand_display_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="nome de exibição"
                    ),
                ),
            ],
            options={
                "verbose_name": "cliente",
            },
        ),
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("unit", "Unidade"),
                            ("sector", "Setor"),
                            ("department", "Departamento"),
                            ("place", "Local"),
                        ],
                        max_length=12,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "unidade organizacional",
                "verbose_name_plural": "unidades organizacionais",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "doc_kind",
                    models.CharField(
                        choices=[("cpf", "CPF"), ("cnpj", "CNPJ")],
                        default="cpf",
                        max_length=6,
                    ),
                ),
                ("doc_number", models.CharField(max_length=14)),
                ("roles", models.JSONField(blank=True, default=list)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "council",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="conselho"
                    ),
                ),
                (
                    "council_state",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="UF do conselho"
                    ),
                ),
                (
                    "council_number",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="registro"
                    ),
                ),
                (
                    "professional_title",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="título profissional"
                    ),
                ),
                ("signature_image_key", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "verbose_name": "pessoa",
            },
        ),
    ]
