# Generated by Django 5.1.15 on 2026-08-17 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orgunit",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="org_units",
                to="clientes.client",
            ),
        ),
        migrations.AddField(
            model_name="orgunit",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orgunit",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="clientes.orgunit",
            ),
        ),
        migrations.AddField(
            model_name="orgunit",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="orgunit",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(
                fields=["tenant", "legal_name"], name="clientes_cl_tenant__55aca2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="client",
            constraint=models.UniqueConstraint(
                fields=("tenant", "tax_id"), name="clientes_client_cnpj_unico"
            ),
        ),
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(
                fields=["tenant", "client", "kind"],
                name="clientes_or_tenant__7787e2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orgunit",
            index=models.Index(
                fields=["parent"], name="clientes_or_parent__7d38a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["tenant", "name"], name="clientes_pe_tenant__e379bd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                fields=("tenant", "doc_kind", "doc_number"),
                name="clientes_person_doc_unico",
            ),
        ),
    ]
