# Generated by Django 5.1.15 on 2026-08-21 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ativos", "0001_initial"),
        ("clientes", "0001_initial"),
        ("core", "0001_initial"),
        ("documentos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=40, verbose_name="número")),
                (
                    "template_code",
                    models.CharField(max_length=10, verbose_name="template"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planejado"),
                            ("running", "Em execução"),
                            ("done", "Concluído"),
                            ("partial", "Concluído com falhas"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="planned",
                        max_length=10,
                    ),
                ),
                (
                    "requested_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="solicitados"
                    ),
                ),
                (
                    "published_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="publicados"
                    ),
                ),
                (
                    "failed_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="falhos"),
                ),
                (
                    "skipped_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="não elegíveis"
                    ),
                ),
                (
                    "plan_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="plano no momento do pedido",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issue_batches",
                        to="clientes.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "lote de emissão",
                "verbose_name_plural": "lotes de emissão",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="IssueBatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Na fila"),
                            ("published", "Publicado"),
                            ("failed", "Falhou"),
                            ("skipped", "Não elegível"),
                        ],
                        default="queued",
                        max_length=10,
                    ),
                ),
                (
                    "rules",
                    models.JSONField(
                        blank=True, default=list, verbose_name="regras que impediram"
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lotes.issuebatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_items",
                        to="documentos.document",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_items",
                        to="ativos.machine",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "item de lote",
                "verbose_name_plural": "itens de lote",
                "ordering": ("machine__name",),
            },
        ),
        migrations.AddIndex(
            model_name="issuebatch",
            index=models.Index(
                fields=["tenant", "-created_at"], name="lotes_issue_tenant__d7eb49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="issuebatch",
            index=models.Index(
                fields=["tenant", "status"], name="lotes_issue_tenant__4e3b3e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="issuebatch",
            constraint=models.UniqueConstraint(
                fields=("tenant", "number"),
                name="lotes_issuebatch_numero_unico_por_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="issuebatchitem",
            index=models.Index(
                fields=["tenant", "batch", "status"],
                name="lotes_issue_tenant__007846_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuebatchitem",
            constraint=models.UniqueConstraint(
                fields=("batch", "machine"),
                name="lotes_issuebatchitem_maquina_unica_no_lote",
            ),
        ),
    ]
