# Generated by Django 5.1.15 on 2026-08-21 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ativos", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template_code",
                    models.CharField(max_length=10, verbose_name="template"),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="número do documento"
                    ),
                ),
                ("title", models.CharField(max_length=220, verbose_name="título")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("blocked", "Bloqueado pelo verificador"),
                            ("ready", "Pronto para publicar"),
                            ("published", "Publicado"),
                            ("superseded", "Substituído por revisão"),
                            ("void", "Anulado"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="ativos.machine",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="ativos.project",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "documento",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="DocumentVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField(verbose_name="versão")),
                (
                    "content_hash",
                    models.CharField(max_length=64, verbose_name="hash do conteúdo"),
                ),
                (
                    "context_snapshot",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="contexto congelado"
                    ),
                ),
                (
                    "verification_snapshot",
                    models.JSONField(
                        blank=True, default=list, verbose_name="verificação no ato"
                    ),
                ),
                (
                    "method_versions",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="versões de método"
                    ),
                ),
                (
                    "pdf_key",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="chave no armazenamento",
                    ),
                ),
                (
                    "pdf_sha256",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="hash do binário"
                    ),
                ),
                (
                    "pdf_bytes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="tamanho do PDF"
                    ),
                ),
                (
                    "page_count",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="páginas"
                    ),
                ),
                (
                    "render_status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando composição"),
                            ("rendered", "PDF composto"),
                            ("failed", "Falha na composição"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("render_error", models.TextField(blank=True)),
                (
                    "signature_status",
                    models.CharField(
                        choices=[
                            ("none", "Sem assinatura"),
                            ("pending", "Aguardando assinatura"),
                            ("signed", "Assinado"),
                            ("failed", "Falha na assinatura"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                (
                    "signature_track",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="trilha de assinatura"
                    ),
                ),
                ("signature", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(verbose_name="publicado em")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documentos.document",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "versão de documento",
                "verbose_name_plural": "versões de documento",
                "ordering": ("-number",),
            },
        ),
        migrations.AddField(
            model_name="document",
            name="current_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="documentos.documentversion",
            ),
        ),
        migrations.CreateModel(
            name="PublicationBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rule", models.CharField(max_length=10, verbose_name="regra")),
                ("severity", models.CharField(max_length=6, verbose_name="severidade")),
                ("message", models.TextField(verbose_name="mensagem")),
                ("entity", models.JSONField(blank=True, default=dict)),
                (
                    "fix_path",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="caminho de correção"
                    ),
                ),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="documentos.document",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "bloqueio de publicação",
                "verbose_name_plural": "bloqueios de publicação",
                "ordering": ("severity", "rule"),
            },
        ),
        migrations.AddIndex(
            model_name="documentversion",
            index=models.Index(
                fields=["tenant", "-published_at"],
                name="documentos__tenant__138642_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentversion",
            constraint=models.UniqueConstraint(
                fields=("document", "number"), name="documentos_versao_unica"
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "machine", "template_code"],
                name="documentos__tenant__5e20a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["tenant", "status"], name="documentos__tenant__02a7d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationblock",
            index=models.Index(
                fields=["tenant", "document", "resolved_at"],
                name="documentos__tenant__8e75e0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="publicationblock",
            index=models.Index(
                fields=["tenant", "rule"], name="documentos__tenant__1a1d28_idx"
            ),
        ),
    ]
