# Generated by Django 5.1.15 on 2026-08-21 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        max_length=120, verbose_name="identificação do aparelho"
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        max_length=120, verbose_name="id informado pelo aparelho"
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Ativo"),
                            ("revoked", "Revogado"),
                            ("expired", "Expirado"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("paired_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="expira em")),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "aparelho de campo",
                "verbose_name_plural": "aparelhos de campo",
            },
        ),
        migrations.CreateModel(
            name="FieldPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file_key",
                    models.CharField(
                        max_length=300, verbose_name="chave no armazenamento"
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("overview", "Visão geral"),
                            ("finding", "Constatação"),
                            ("nameplate", "Placa de identificação"),
                            ("device", "Dispositivo de segurança"),
                            ("lockout", "Ponto de bloqueio"),
                        ],
                        default="finding",
                        max_length=12,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="legenda"
                    ),
                ),
                (
                    "taken_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="registrada em"
                    ),
                ),
                (
                    "geo",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="coordenada"
                    ),
                ),
                ("bytes_size", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "foto de campo",
                "verbose_name_plural": "fotos de campo",
            },
        ),
        migrations.CreateModel(
            name="SyncBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_batch_uuid",
                    models.UUIDField(verbose_name="uuid do lote no aparelho"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Aplicado"),
                            ("partial", "Parcial"),
                            ("rejected", "Recusado"),
                            ("empty", "Vazio"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="recebido em"),
                ),
                (
                    "device_reported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="hora do aparelho"
                    ),
                ),
                (
                    "clock_skew_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="desvio de relógio (s)"
                    ),
                ),
                ("applied_count", models.PositiveSmallIntegerField(default=0)),
                ("failed_count", models.PositiveSmallIntegerField(default=0)),
                ("conflict_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="resposta devolvida"
                    ),
                ),
            ],
            options={
                "verbose_name": "lote de sincronização",
                "verbose_name_plural": "lotes de sincronização",
                "ordering": ("-received_at",),
            },
        ),
        migrations.CreateModel(
            name="SyncRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_uuid",
                    models.UUIDField(verbose_name="uuid do registro no aparelho"),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("item_result", "Resposta de checklist"),
                            ("photo", "Foto"),
                            ("field_hazard", "Perigo observado em campo"),
                        ],
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "Aplicado"),
                            ("failed", "Falhou"),
                            ("conflict", "Em conflito"),
                            ("duplicate", "Duplicado — já aplicado antes"),
                        ],
                        max_length=10,
                    ),
                ),
                ("failure_code", models.CharField(blank=True, max_length=40)),
                ("failure_message", models.TextField(blank=True)),
                ("applied_table", models.CharField(blank=True, max_length=64)),
                ("applied_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "registro de sincronização",
                "verbose_name_plural": "registros de sincronização",
            },
        ),
    ]
