# Generated by Django 5.1.15 on 2026-08-21 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ativos", "0002_initial"),
        ("campo", "0001_initial"),
        ("checklists", "0001_initial"),
        ("core", "0001_initial"),
        ("risco", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="operator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fieldphoto",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fieldphoto",
            name="hazard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="risco.hazard",
            ),
        ),
        migrations.AddField(
            model_name="fieldphoto",
            name="item_result",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="checklists.itemresultrecord",
            ),
        ),
        migrations.AddField(
            model_name="fieldphoto",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="field_photos",
                to="ativos.machine",
            ),
        ),
        migrations.AddField(
            model_name="fieldphoto",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="fieldphoto",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="syncbatch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="syncbatch",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batches",
                to="campo.device",
            ),
        ),
        migrations.AddField(
            model_name="syncbatch",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="syncbatch",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="syncrecord",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="campo.syncbatch",
            ),
        ),
        migrations.AddField(
            model_name="syncrecord",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="syncrecord",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="syncrecord",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fieldphoto",
            name="record",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photo",
                to="campo.syncrecord",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["tenant", "status"], name="campo_devic_tenant__a03aff_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("tenant", "device_id"),
                name="campo_device_id_unico_por_tenant_ativo",
            ),
        ),
        migrations.AddIndex(
            model_name="syncbatch",
            index=models.Index(
                fields=["tenant", "-received_at"], name="campo_syncb_tenant__31ed4c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncbatch",
            index=models.Index(
                fields=["tenant", "status"], name="campo_syncb_tenant__f67049_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="syncbatch",
            constraint=models.UniqueConstraint(
                fields=("tenant", "client_batch_uuid"),
                name="campo_syncbatch_uuid_unico_por_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="syncrecord",
            index=models.Index(
                fields=["tenant", "batch", "status"],
                name="campo_syncr_tenant__07e9a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syncrecord",
            index=models.Index(
                fields=["tenant", "status", "record_type"],
                name="campo_syncr_tenant__fa7b8e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="syncrecord",
            constraint=models.UniqueConstraint(
                fields=("tenant", "client_uuid"),
                name="campo_syncrecord_uuid_unico_por_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldphoto",
            index=models.Index(
                fields=["tenant", "machine", "slot"],
                name="campo_field_tenant__eef8cf_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="fieldphoto",
            constraint=models.UniqueConstraint(
                fields=("tenant", "file_key"), name="campo_fieldphoto_chave_unica"
            ),
        ),
    ]
