# Generated by Django 5.1.15 on 2026-08-21 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ativos", "0002_initial"),
        ("checklists", "0002_initial"),
        ("clientes", "0002_initial"),
        ("core", "0001_initial"),
        ("risco", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=40, verbose_name="número")),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "opened_at",
                    models.DateField(auto_now_add=True, verbose_name="aberto em"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_plans",
                        to="ativos.machine",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "plano de ação",
                "verbose_name_plural": "planos de ação",
            },
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, verbose_name="código")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("recommendation", "Recomendação de apreciação"),
                            ("checklist", "Item de checklist não conforme"),
                            ("field", "Observação de campo"),
                            ("manual", "Lançamento manual"),
                        ],
                        max_length=16,
                    ),
                ),
                ("text", models.TextField(verbose_name="o que fazer")),
                ("deadline", models.DateField(verbose_name="prazo")),
                (
                    "suggested_days",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="prazo sugerido (dias)"
                    ),
                ),
                (
                    "deadline_rationale",
                    models.TextField(blank=True, verbose_name="justificativa do prazo"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberta"),
                            ("in_progress", "Em execução"),
                            ("done", "Concluída"),
                            ("cancelled", "Cancelada"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                (
                    "completed_on",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="concluída em (data do fato)",
                    ),
                ),
                (
                    "cancel_reason",
                    models.TextField(blank=True, verbose_name="motivo do cancelamento"),
                ),
                (
                    "blocking",
                    models.BooleanField(
                        default=False, verbose_name="bloqueia publicação"
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="custo estimado",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hazard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="risco.hazard",
                    ),
                ),
                (
                    "item_result",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="checklists.itemresultrecord",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="clientes.person",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="risco.recommendation",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="planos.actionplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "ação",
                "verbose_name_plural": "ações",
                "ordering": ("deadline", "code"),
            },
        ),
        migrations.CreateModel(
            name="DeadlineChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous", models.DateField(verbose_name="prazo anterior")),
                ("current", models.DateField(verbose_name="novo prazo")),
                ("reason", models.TextField(verbose_name="justificativa")),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deadline_changes",
                        to="planos.action",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "repactuação de prazo",
                "verbose_name_plural": "repactuações de prazo",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("photo", "Foto"),
                            ("invoice", "Nota fiscal"),
                            ("certificate", "Certificado"),
                            ("report", "Laudo ou relatório"),
                            ("other", "Outro"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "file_key",
                    models.CharField(
                        max_length=300, verbose_name="chave no armazenamento"
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="hash do arquivo"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="descrição"
                    ),
                ),
                (
                    "occurred_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="data do fato"
                    ),
                ),
                ("bytes_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="planos.action",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "evidência",
                "verbose_name_plural": "evidências",
            },
        ),
        migrations.AddIndex(
            model_name="actionplan",
            index=models.Index(
                fields=["tenant", "machine"], name="planos_acti_tenant__385f38_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="actionplan",
            constraint=models.UniqueConstraint(
                fields=("tenant", "number"),
                name="planos_actionplan_numero_unico_por_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["tenant", "plan", "status"],
                name="planos_acti_tenant__da383f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["tenant", "deadline"], name="planos_acti_tenant__5ee3bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="action",
            index=models.Index(
                fields=["tenant", "owner", "status"],
                name="planos_acti_tenant__72bcc9_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.UniqueConstraint(
                fields=("tenant", "code"), name="planos_action_codigo_unico_por_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.UniqueConstraint(
                condition=models.Q(("recommendation__isnull", False)),
                fields=("recommendation",),
                name="planos_action_uma_por_recomendacao",
            ),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.UniqueConstraint(
                condition=models.Q(("item_result__isnull", False)),
                fields=("item_result",),
                name="planos_action_uma_por_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("completed_on__isnull", False), ("status", "done")),
                    models.Q(
                        models.Q(("status", "done"), _negated=True),
                        ("completed_on__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="planos_action_concluida_exige_data_do_fato",
            ),
        ),
        migrations.AddConstraint(
            model_name="action",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "cancelled"), _negated=True),
                    models.Q(("cancel_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="planos_action_cancelamento_exige_motivo",
            ),
        ),
        migrations.AddIndex(
            model_name="deadlinechange",
            index=models.Index(
                fields=["tenant", "action"], name="planos_dead_tenant__8fa3c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["tenant", "action"], name="planos_evid_tenant__5abaa4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="evidence",
            constraint=models.UniqueConstraint(
                fields=("tenant", "file_key"), name="planos_evidence_chave_unica"
            ),
        ),
    ]
